[package]
name = "dfrobot_c1001"
version = "0.1.0"
edition = "2021"

[dependencies]
serialport = { version = "4.7.1", default-features = false, features = ["serde"] }
thiserror = { version = "2.0.12", features = ["std"] }
tracing = "0.1.41"
